### ISSUE TITLE
SFML

### ISSUE THREAD

**Issue by DoctorVWA** [michaelfairley/rust-imgui-opengl-renderer#10]
Hello, is it possible to use this with rust SFML? there isn't a function in sfml for getting proc address, but it can create a opengl context. 

If you are wondering why I don't test it myself, that's because my SFML game runs on opengl 2.1, and my computer can't run open gl 3+, there's an open issue open for this as well, I just want to know if I can use it with sfml, and if it's worth forking it and trying myself to get it working on opengl 2.x.

Thanks ;)

**Comment by michaelfairley** [comment]
It looks like SFML's `Context` has a [`getFunction`](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Context.php#a998980d311effdf6223ce40d934c23c3), but it's not exposed from the Rust wrapper :confused:. With that method, this library should work fine with SFML.

**Comment by DoctorVWA** [comment]
Hello, really thanks for the quick reply, I didn't saw it before, one question, the string passed in the callback is exactly what? 

Also I saw there in sfml-rust issues this [milestone](https://github.com/jeremyletang/rust-sfml/issues/142), looks likes they implemented `Context` on it, but didn't exposed this function, I gonna try to find someone who exposed this method, and send it here for further people trying to use your's crate.

Keep it up! Find people who cares about issues on github is a hard task sometimes.

**Comment by DoctorVWA** [comment]
Actually I belive I found an workaround for it, I was reading the code of your crate and saw this function `[build_rgba32_texture()](https://github.com/michaelfairley/rust-imgui-opengl-renderer/blob/master/src/lib.rs#L119)`, there's this [function](https://docs.rs/sfml/0.15.1/sfml/graphics/struct.Image.html#method.create_from_pixels) on sfml, that maybe can be used for this part, but for the rest, I don't see any workaround without actually using the gl context.

**Comment by DoctorVWA** [comment]
Really thanks for the help, looks like it's a root problem with the bindings of SFML, they use CSFML, which doesn't implement the getFunction method on the [context](https://github.com/SFML/CSFML/blob/05847516fd94051641ccb525df0bed050b00fe4e/src/SFML/Window/Context.cpp), I really appreciate your help, gonna close the issue for now, if I manage to get it working, I'll open a PR for opengl 2.0, thanks for everything, bye :)
