### ISSUE TITLE
vertex array IDs are leaked

### ISSUE THREAD

**Issue by rasky** [michaelfairley/rust-imgui-opengl-renderer#4]
`gl.GenVertexArrays` is called every frame, but `glDeleteVertexArrays` is never called. It should be probably sufficient to create the vao once, store the id, and reuse every frame.

**Comment by michaelfairley** [comment]
Ah! Thanks! Fixed in c8fa1202cf7d25e90f13ea2e19b5048f1ad888e1, and released in 0.3.1
