### ISSUE TITLE
Textures?

### ISSUE THREAD

**Issue by JMS55** [michaelfairley/rust-imgui-opengl-renderer#6]
Image needs a TextureId. Is there some way to get that from a sdl2 Texture? How can this be done?

**Comment by michaelfairley** [comment]
SDL2 doesn't seem to provide a way to get the underlying OpenGL texture id for an SDL2 Texture, so I don't think this library is usable if you want custom images while using the SDL2 renderer.

**Comment by JMS55** [comment]
No problem, I ended up moving to glium anyways
